name: Run Swift Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests Sequentially
    runs-on: macos-latest-large
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Run Tests (No Parallel)
        run: swift test --no-parallel
